### ISSUE TITLE
Does this work in GDL

### ISSUE THREAD

**Issue by olexandr-konovalov** [SEDMORPH/PawlikMorph#4]
I learned that GDL (The GNU Data Language) is a free alternative to IDL. Do you know if this code works under GDL? If not, might be interesting to check. If it works, that may be very useful - one could then add some tests and run them on public continuous integration services such as [Travis CI](https://travis-ci.org/).

**Comment by lagopede** [comment]
Almost certainly not unfortunately. GDL misses quite a lot of functionality of IDL, and is often much slower.
